/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Chapter = IDL.Record({
  'subjectName' : IDL.Text,
  'name' : IDL.Text,
  'totalTopics' : IDL.Nat,
  'notesPdf' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'completedTopics' : IDL.Nat,
});
export const Test = IDL.Record({
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'scoredMarks' : IDL.Opt(IDL.Nat),
  'isCompleted' : IDL.Bool,
  'date' : Time,
  'name' : IDL.Text,
  'chapters' : IDL.Vec(IDL.Text),
});
export const RevisionTopic = IDL.Record({
  'topic' : IDL.Text,
  'subject' : IDL.Text,
  'scheduledDate' : Time,
  'isComplete' : IDL.Bool,
});
export const StudySession = IDL.Record({
  'topicsCovered' : IDL.Text,
  'subject' : IDL.Text,
  'date' : Time,
  'hoursStudied' : IDL.Nat,
});
export const Subject = IDL.Record({
  'targetCompletionDate' : Time,
  'name' : IDL.Text,
  'totalTopics' : IDL.Nat,
  'completedTopics' : IDL.Nat,
});
export const Goal = IDL.Record({ 'actual' : IDL.Nat, 'dailyGoal' : IDL.Nat });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addRevisionTopic' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'addStudySession' : IDL.Func([Time, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Nat, Time], [], []),
  'addTest' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteSubject' : IDL.Func([IDL.Text], [], []),
  'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getArchivedChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getChaptersBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
  'getCompletedTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getPdfBlobs' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getPdfPath' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getPendingTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getRevisionSchedule' : IDL.Func([], [IDL.Vec(RevisionTopic)], ['query']),
  'getRevisionSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSessionSummaries' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getSuggestedSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getTodayGoal' : IDL.Func([], [Goal], ['query']),
  'incrementTodayGoal' : IDL.Func([], [], []),
  'markRevisionComplete' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveSessionSummary' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setTodayGoal' : IDL.Func([IDL.Nat], [], []),
  'updateChapterTopics' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateCompletedTopics' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateTestScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadPdf' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Chapter = IDL.Record({
    'subjectName' : IDL.Text,
    'name' : IDL.Text,
    'totalTopics' : IDL.Nat,
    'notesPdf' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'completedTopics' : IDL.Nat,
  });
  const Test = IDL.Record({
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'scoredMarks' : IDL.Opt(IDL.Nat),
    'isCompleted' : IDL.Bool,
    'date' : Time,
    'name' : IDL.Text,
    'chapters' : IDL.Vec(IDL.Text),
  });
  const RevisionTopic = IDL.Record({
    'topic' : IDL.Text,
    'subject' : IDL.Text,
    'scheduledDate' : Time,
    'isComplete' : IDL.Bool,
  });
  const StudySession = IDL.Record({
    'topicsCovered' : IDL.Text,
    'subject' : IDL.Text,
    'date' : Time,
    'hoursStudied' : IDL.Nat,
  });
  const Subject = IDL.Record({
    'targetCompletionDate' : Time,
    'name' : IDL.Text,
    'totalTopics' : IDL.Nat,
    'completedTopics' : IDL.Nat,
  });
  const Goal = IDL.Record({ 'actual' : IDL.Nat, 'dailyGoal' : IDL.Nat });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addRevisionTopic' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'addStudySession' : IDL.Func([Time, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Nat, Time], [], []),
    'addTest' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteSubject' : IDL.Func([IDL.Text], [], []),
    'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getArchivedChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getChaptersBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Chapter)],
        ['query'],
      ),
    'getCompletedTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getPdfBlobs' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getPdfPath' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getPendingTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getRevisionSchedule' : IDL.Func([], [IDL.Vec(RevisionTopic)], ['query']),
    'getRevisionSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSessionSummaries' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getSuggestedSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getTodayGoal' : IDL.Func([], [Goal], ['query']),
    'incrementTodayGoal' : IDL.Func([], [], []),
    'markRevisionComplete' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveSessionSummary' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setTodayGoal' : IDL.Func([IDL.Nat], [], []),
    'updateChapterTopics' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateCompletedTopics' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateTestScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadPdf' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };