/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'subjectName' : string,
  'name' : string,
  'totalTopics' : bigint,
  'notesPdf' : [] | [Uint8Array],
  'completedTopics' : bigint,
}
export interface Goal { 'actual' : bigint, 'dailyGoal' : bigint }
export interface RevisionTopic {
  'topic' : string,
  'subject' : string,
  'scheduledDate' : Time,
  'isComplete' : boolean,
}
export interface StudySession {
  'topicsCovered' : string,
  'subject' : string,
  'date' : Time,
  'hoursStudied' : bigint,
}
export interface Subject {
  'targetCompletionDate' : Time,
  'name' : string,
  'totalTopics' : bigint,
  'completedTopics' : bigint,
}
export interface Test {
  'totalMarks' : bigint,
  'subject' : string,
  'scoredMarks' : [] | [bigint],
  'isCompleted' : boolean,
  'date' : Time,
  'name' : string,
  'chapters' : Array<string>,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addChapter' : ActorMethod<[string, string, bigint], undefined>,
  'addRevisionTopic' : ActorMethod<[string, string, Time], undefined>,
  'addStudySession' : ActorMethod<[Time, string, bigint, string], undefined>,
  'addSubject' : ActorMethod<[string, bigint, Time], undefined>,
  'addTest' : ActorMethod<
    [string, string, Time, bigint, Array<string>],
    undefined
  >,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'getAllChapters' : ActorMethod<[], Array<Chapter>>,
  'getArchivedChapters' : ActorMethod<[], Array<Chapter>>,
  'getChaptersBySubject' : ActorMethod<[string], Array<Chapter>>,
  'getCompletedTests' : ActorMethod<[], Array<Test>>,
  'getPdfBlobs' : ActorMethod<[string], [] | [Uint8Array]>,
  'getPdfPath' : ActorMethod<[string], [] | [Uint8Array]>,
  'getPendingTests' : ActorMethod<[], Array<Test>>,
  'getRevisionSchedule' : ActorMethod<[], Array<RevisionTopic>>,
  'getRevisionSuggestions' : ActorMethod<[], Array<string>>,
  'getSessionSummaries' : ActorMethod<[], Array<string>>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getSuggestedSubjects' : ActorMethod<[], Array<string>>,
  'getTests' : ActorMethod<[], Array<Test>>,
  'getTodayGoal' : ActorMethod<[], Goal>,
  'incrementTodayGoal' : ActorMethod<[], undefined>,
  'markRevisionComplete' : ActorMethod<[string, string], undefined>,
  'saveSessionSummary' : ActorMethod<[string, string], undefined>,
  'setTodayGoal' : ActorMethod<[bigint], undefined>,
  'updateChapterTopics' : ActorMethod<[string, bigint], undefined>,
  'updateCompletedTopics' : ActorMethod<[string, bigint], undefined>,
  'updateTestScore' : ActorMethod<[string, bigint], undefined>,
  'uploadPdf' : ActorMethod<[Uint8Array, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];