/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email?: string;
    avatarUrl?: string;
}
export interface Goal {
    actual: bigint;
    dailyGoal: bigint;
}
export type Time = bigint;
export interface Reward {
    id: string;
    unlockDate?: Time;
    name: string;
    description: string;
    unlockCondition: string;
    progress?: bigint;
    target?: bigint;
    isUnlocked: boolean;
    bonusXp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Test {
    totalMarks: bigint;
    subject: string;
    scoredMarks?: bigint;
    isCompleted: boolean;
    date: Time;
    name: string;
    chapters: Array<string>;
}
export interface QuestionPaper {
    pdfBlob: Uint8Array;
    name: string;
    uploadDate: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProgress {
    xp: bigint;
    level: bigint;
    lastStudyDate: Time;
    currentStreak: bigint;
}
export interface RevisionTopic {
    topic: string;
    subject: string;
    scheduledDate: Time;
    isComplete: boolean;
}
export interface Chapter {
    subjectName: string;
    name: string;
    totalTopics: bigint;
    notesPdf?: Uint8Array;
    completedTopics: bigint;
}
export interface SessionSummary {
    content: string;
}
export interface StudySession {
    topicsCovered: string;
    subject: string;
    date: Time;
    hoursStudied: bigint;
}
export interface Subject {
    targetCompletionDate: Time;
    name: string;
    totalTopics: bigint;
    completedTopics: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface XPResponse {
    xp: bigint;
    level: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChapter(chapter: Chapter): Promise<void>;
    addQuestionPaper(paper: QuestionPaper): Promise<void>;
    addRevisionTopic(topic: RevisionTopic): Promise<void>;
    addReward(reward: Reward): Promise<void>;
    addStudySession(session: StudySession): Promise<void>;
    addSubject(subject: Subject): Promise<void>;
    addTest(test: Test): Promise<void>;
    addXP(amount: bigint): Promise<XPResponse>;
    archiveChapter(chapterName: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteQuestionPaper(paperName: string): Promise<void>;
    deleteSubject(subjectName: string): Promise<void>;
    deleteTest(testName: string): Promise<void>;
    getArchivedChapters(): Promise<Array<Chapter>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChapters(): Promise<Array<Chapter>>;
    getCompletedTests(): Promise<Array<Test>>;
    getDailyGoal(): Promise<Goal>;
    getNonCompletedTests(): Promise<Array<Test>>;
    getQuestionPapers(): Promise<Array<QuestionPaper>>;
    getRevisionTopics(): Promise<Array<RevisionTopic>>;
    getRewards(): Promise<Array<Reward>>;
    getSessionSummary(key: string): Promise<SessionSummary | null>;
    getStudySessions(): Promise<Array<StudySession>>;
    getSubjects(): Promise<Array<Subject>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProgress(): Promise<UserProgress>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveSessionSummary(key: string, summary: SessionSummary): Promise<void>;
    setDailyGoal(goal: bigint): Promise<void>;
    updateChapter(chapter: Chapter): Promise<void>;
    updateDailyActual(actual: bigint): Promise<void>;
    updateReward(reward: Reward): Promise<void>;
    updateSubject(subject: Subject): Promise<void>;
    updateTest(test: Test): Promise<void>;
    updateUserProgress(progress: UserProgress): Promise<void>;
}
import type { Chapter as _Chapter, Reward as _Reward, SessionSummary as _SessionSummary, Test as _Test, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChapter(arg0: Chapter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChapter(to_candid_Chapter_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChapter(to_candid_Chapter_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addQuestionPaper(arg0: QuestionPaper): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestionPaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestionPaper(arg0);
            return result;
        }
    }
    async addRevisionTopic(arg0: RevisionTopic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRevisionTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRevisionTopic(arg0);
            return result;
        }
    }
    async addReward(arg0: Reward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReward(to_candid_Reward_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReward(to_candid_Reward_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudySession(arg0: StudySession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudySession(arg0);
            return result;
        }
    }
    async addSubject(arg0: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0);
            return result;
        }
    }
    async addTest(arg0: Test): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTest(to_candid_Test_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTest(to_candid_Test_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addXP(arg0: bigint): Promise<XPResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addXP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addXP(arg0);
            return result;
        }
    }
    async archiveChapter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveChapter(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteQuestionPaper(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestionPaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestionPaper(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async deleteTest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0);
            return result;
        }
    }
    async getArchivedChapters(): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedChapters();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedChapters();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapters(): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapters();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapters();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedTests(): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedTests();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedTests();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyGoal(): Promise<Goal> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyGoal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyGoal();
            return result;
        }
    }
    async getNonCompletedTests(): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNonCompletedTests();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNonCompletedTests();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionPapers(): Promise<Array<QuestionPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionPapers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionPapers();
            return result;
        }
    }
    async getRevisionTopics(): Promise<Array<RevisionTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevisionTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevisionTopics();
            return result;
        }
    }
    async getRewards(): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionSummary(arg0: string): Promise<SessionSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionSummary(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionSummary(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudySessions(): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudySessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudySessions();
            return result;
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProgress(): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSessionSummary(arg0: string, arg1: SessionSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSessionSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSessionSummary(arg0, arg1);
            return result;
        }
    }
    async setDailyGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyGoal(arg0);
            return result;
        }
    }
    async updateChapter(arg0: Chapter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(to_candid_Chapter_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(to_candid_Chapter_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDailyActual(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyActual(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyActual(arg0);
            return result;
        }
    }
    async updateReward(arg0: Reward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReward(to_candid_Reward_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReward(to_candid_Reward_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSubject(arg0: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0);
            return result;
        }
    }
    async updateTest(arg0: Test): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(to_candid_Test_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(to_candid_Test_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserProgress(arg0: UserProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProgress(arg0);
            return result;
        }
    }
}
function from_candid_Chapter_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chapter): Chapter {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Reward_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reward): Reward {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Test_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Test): Test {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionSummary]): SessionSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjectName: string;
    name: string;
    totalTopics: bigint;
    notesPdf: [] | [Uint8Array];
    completedTopics: bigint;
}): {
    subjectName: string;
    name: string;
    totalTopics: bigint;
    notesPdf?: Uint8Array;
    completedTopics: bigint;
} {
    return {
        subjectName: value.subjectName,
        name: value.name,
        totalTopics: value.totalTopics,
        notesPdf: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.notesPdf)),
        completedTopics: value.completedTopics
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    avatarUrl: [] | [string];
}): {
    name: string;
    email?: string;
    avatarUrl?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.email)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMarks: bigint;
    subject: string;
    scoredMarks: [] | [bigint];
    isCompleted: boolean;
    date: _Time;
    name: string;
    chapters: Array<string>;
}): {
    totalMarks: bigint;
    subject: string;
    scoredMarks?: bigint;
    isCompleted: boolean;
    date: Time;
    name: string;
    chapters: Array<string>;
} {
    return {
        totalMarks: value.totalMarks,
        subject: value.subject,
        scoredMarks: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.scoredMarks)),
        isCompleted: value.isCompleted,
        date: value.date,
        name: value.name,
        chapters: value.chapters
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    unlockDate: [] | [_Time];
    name: string;
    description: string;
    unlockCondition: string;
    progress: [] | [bigint];
    target: [] | [bigint];
    isUnlocked: boolean;
    bonusXp: bigint;
}): {
    id: string;
    unlockDate?: Time;
    name: string;
    description: string;
    unlockCondition: string;
    progress?: bigint;
    target?: bigint;
    isUnlocked: boolean;
    bonusXp: bigint;
} {
    return {
        id: value.id,
        unlockDate: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.unlockDate)),
        name: value.name,
        description: value.description,
        unlockCondition: value.unlockCondition,
        progress: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.progress)),
        target: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.target)),
        isUnlocked: value.isUnlocked,
        bonusXp: value.bonusXp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chapter>): Array<Chapter> {
    return value.map((x)=>from_candid_Chapter_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Test>): Array<Test> {
    return value.map((x)=>from_candid_Test_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reward>): Array<Reward> {
    return value.map((x)=>from_candid_Reward_n30(_uploadFile, _downloadFile, x));
}
function to_candid_Chapter_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Chapter): _Chapter {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Reward_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reward): _Reward {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Test_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Test): _Test {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    unlockDate?: Time;
    name: string;
    description: string;
    unlockCondition: string;
    progress?: bigint;
    target?: bigint;
    isUnlocked: boolean;
    bonusXp: bigint;
}): {
    id: string;
    unlockDate: [] | [_Time];
    name: string;
    description: string;
    unlockCondition: string;
    progress: [] | [bigint];
    target: [] | [bigint];
    isUnlocked: boolean;
    bonusXp: bigint;
} {
    return {
        id: value.id,
        unlockDate: value.unlockDate ? candid_some(value.unlockDate) : candid_none(),
        name: value.name,
        description: value.description,
        unlockCondition: value.unlockCondition,
        progress: value.progress ? candid_some(value.progress) : candid_none(),
        target: value.target ? candid_some(value.target) : candid_none(),
        isUnlocked: value.isUnlocked,
        bonusXp: value.bonusXp
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMarks: bigint;
    subject: string;
    scoredMarks?: bigint;
    isCompleted: boolean;
    date: Time;
    name: string;
    chapters: Array<string>;
}): {
    totalMarks: bigint;
    subject: string;
    scoredMarks: [] | [bigint];
    isCompleted: boolean;
    date: _Time;
    name: string;
    chapters: Array<string>;
} {
    return {
        totalMarks: value.totalMarks,
        subject: value.subject,
        scoredMarks: value.scoredMarks ? candid_some(value.scoredMarks) : candid_none(),
        isCompleted: value.isCompleted,
        date: value.date,
        name: value.name,
        chapters: value.chapters
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    avatarUrl?: string;
}): {
    name: string;
    email: [] | [string];
    avatarUrl: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjectName: string;
    name: string;
    totalTopics: bigint;
    notesPdf?: Uint8Array;
    completedTopics: bigint;
}): {
    subjectName: string;
    name: string;
    totalTopics: bigint;
    notesPdf: [] | [Uint8Array];
    completedTopics: bigint;
} {
    return {
        subjectName: value.subjectName,
        name: value.name,
        totalTopics: value.totalTopics,
        notesPdf: value.notesPdf ? candid_some(value.notesPdf) : candid_none(),
        completedTopics: value.completedTopics
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
