// CA Final subjects and chapters data from ICAI
// Source: https://boslive.icai.org/study_material_new_paper_details.php?c=final&language=English&year=Applicable%20for%20May%202025,%20September%202025%20and%20January%202026%20Exam%20Onwards

export interface CASubjectData {
  name: string;
  totalTopics: number;
  chapters: string[];
}

export const CA_FINAL_SUBJECTS: CASubjectData[] = [
  {
    name: "Paper 1: Financial Reporting",
    totalTopics: 0,
    chapters: [
      "Chapter 1: Conceptual Framework for Financial Reporting",
      "Chapter 2: Accounting Standards",
      "Chapter 3: Schedule III",
      "Chapter 4: Company Accounts",
      "Chapter 5: Consolidated Financial Statements",
      "Chapter 6: Accounting for Business Combinations",
      "Chapter 7: Accounting for Dissolution of Partnership Firms",
      "Chapter 8: Accounting for Amalgamation of Partnership Firms",
      "Chapter 9: Accounting for Conversion of Partnership Firm into a Company",
      "Chapter 10: Financial Statements of Insurance Companies",
      "Chapter 11: Financial Statements of Banking Companies",
      "Chapter 12: Financial Statements of Non-Banking Finance Companies",
      "Chapter 13: Accounting and Reporting of Financial Instruments",
      "Chapter 14: Share-Based Payments",
      "Chapter 15: Valuation",
      "Chapter 16: Integrated Reporting",
      "Chapter 17: Corporate Social Responsibility Reporting",
    ],
  },
  {
    name: "Paper 2: Advanced Financial Management",
    totalTopics: 0,
    chapters: [
      "Chapter 1: Financial Policy and Corporate Strategy",
      "Chapter 2: Risk Management",
      "Chapter 3: Security Analysis",
      "Chapter 4: Security Valuation",
      "Chapter 5: Portfolio Management",
      "Chapter 6: Securitization",
      "Chapter 7: Mutual Funds",
      "Chapter 8: Derivatives Analysis and Valuation",
      "Chapter 9: Foreign Exchange Exposure and Risk Management",
      "Chapter 10: International Financial Management",
      "Chapter 11: Interest Rate Risk Management",
      "Chapter 12: Business Valuation",
      "Chapter 13: Mergers, Acquisitions and Corporate Restructuring",
      "Chapter 14: Startup Finance",
    ],
  },
  {
    name: "Paper 3: Advanced Auditing, Assurance and Professional Ethics",
    totalTopics: 0,
    chapters: [
      "Chapter 1: Quality Control",
      "Chapter 2: General Auditing Principles and Auditor Responsibilities",
      "Chapter 3: Risk Assessment and Internal Control",
      "Chapter 4: Audit of Items of Financial Statements",
      "Chapter 5: The Company Audit",
      "Chapter 6: Audit Report",
      "Chapter 7: Audit of Consolidated Financial Statements",
      "Chapter 8: Special Features of Audit of Banks",
      "Chapter 9: Audit of Non-Banking Financial Companies",
      "Chapter 10: Audit of Insurance Companies",
      "Chapter 11: Audit of Public Sector Undertakings",
      "Chapter 12: Liabilities of Auditors",
      "Chapter 13: Internal Audit",
      "Chapter 14: Due Diligence, Investigation and Forensic Accounting",
      "Chapter 15: Peer Review and Quality Review",
      "Chapter 16: Professional Ethics",
    ],
  },
  {
    name: "Paper 4: Direct Tax Laws & International Taxation",
    totalTopics: 0,
    chapters: [], // Chapters will be updated later
  },
  {
    name: "Paper 5: Indirect Tax Laws",
    totalTopics: 0,
    chapters: [
      "Chapter 1: GST in India - An Introduction",
      "Chapter 2: Supply under GST",
      "Chapter 3: Charge of GST",
      "Chapter 4: Exemptions from GST",
      "Chapter 5: Place of Supply",
      "Chapter 6: Time of Supply",
      "Chapter 7: Value of Supply",
      "Chapter 8: Input Tax Credit",
      "Chapter 9: Registration",
      "Chapter 10: Tax Invoice, Credit and Debit Notes",
      "Chapter 11: Accounts and Records; E-way Bill",
      "Chapter 12: Payment of Tax",
      "Chapter 13: Electronic Commerce",
      "Chapter 14: Returns",
      "Chapter 15: Import and Export Under GST",
      "Chapter 16: Refunds",
      "Chapter 17: Assessment and Audit",
      "Chapter 18: Inspection, Search, Seizure and Arrest",
      "Chapter 19: Demand and Recovery",
      "Chapter 20: Liability to Pay in Certain Cases",
      "Chapter 21: Offences and Penalties",
      "Chapter 22: Appeals and Revision",
      "Chapter 23: Advance Ruling",
      "Chapter 24: Miscellaneous Provisions",
      "Chapter 25: Customs Law",
      "Chapter 26: Foreign Trade Policy",
    ],
  },
  {
    name: "Paper 6: Integrated Business Solutions",
    totalTopics: 0,
    chapters: [
      "Chapter 1: Corporate and Economic Laws",
      "Chapter 2: Strategic Cost Management and Performance Evaluation",
      "Chapter 3: Risk Management",
      "Chapter 4: Financial Reporting",
      "Chapter 5: Advanced Financial Management",
      "Chapter 6: Advanced Auditing, Assurance and Professional Ethics",
      "Chapter 7: Direct Tax Laws & International Taxation",
      "Chapter 8: Indirect Tax Laws",
    ],
  },
];
