/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Chapter = IDL.Record({
  'subjectName' : IDL.Text,
  'name' : IDL.Text,
  'totalTopics' : IDL.Nat,
  'notesPdf' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'completedTopics' : IDL.Nat,
});
export const Time = IDL.Int;
export const QuestionPaper = IDL.Record({
  'pdfBlob' : IDL.Vec(IDL.Nat8),
  'name' : IDL.Text,
  'uploadDate' : Time,
});
export const RevisionTopic = IDL.Record({
  'topic' : IDL.Text,
  'subject' : IDL.Text,
  'scheduledDate' : Time,
  'isComplete' : IDL.Bool,
});
export const Reward = IDL.Record({
  'id' : IDL.Text,
  'unlockDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'unlockCondition' : IDL.Text,
  'progress' : IDL.Opt(IDL.Nat),
  'target' : IDL.Opt(IDL.Nat),
  'isUnlocked' : IDL.Bool,
  'bonusXp' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'topicsCovered' : IDL.Text,
  'subject' : IDL.Text,
  'date' : Time,
  'hoursStudied' : IDL.Nat,
});
export const Subject = IDL.Record({
  'targetCompletionDate' : Time,
  'name' : IDL.Text,
  'totalTopics' : IDL.Nat,
  'completedTopics' : IDL.Nat,
});
export const Test = IDL.Record({
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'scoredMarks' : IDL.Opt(IDL.Nat),
  'isCompleted' : IDL.Bool,
  'date' : Time,
  'name' : IDL.Text,
  'chapters' : IDL.Vec(IDL.Text),
});
export const XPResponse = IDL.Record({ 'xp' : IDL.Nat, 'level' : IDL.Nat });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const Goal = IDL.Record({ 'actual' : IDL.Nat, 'dailyGoal' : IDL.Nat });
export const SessionSummary = IDL.Record({ 'content' : IDL.Text });
export const UserProgress = IDL.Record({
  'xp' : IDL.Nat,
  'level' : IDL.Nat,
  'lastStudyDate' : Time,
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChapter' : IDL.Func([Chapter], [], []),
  'addQuestionPaper' : IDL.Func([QuestionPaper], [], []),
  'addRevisionTopic' : IDL.Func([RevisionTopic], [], []),
  'addReward' : IDL.Func([Reward], [], []),
  'addStudySession' : IDL.Func([StudySession], [], []),
  'addSubject' : IDL.Func([Subject], [], []),
  'addTest' : IDL.Func([Test], [], []),
  'addXP' : IDL.Func([IDL.Nat], [XPResponse], []),
  'archiveChapter' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteQuestionPaper' : IDL.Func([IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Text], [], []),
  'deleteTest' : IDL.Func([IDL.Text], [], []),
  'getArchivedChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getCompletedTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getDailyGoal' : IDL.Func([], [Goal], ['query']),
  'getNonCompletedTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getQuestionPapers' : IDL.Func([], [IDL.Vec(QuestionPaper)], ['query']),
  'getRevisionTopics' : IDL.Func([], [IDL.Vec(RevisionTopic)], ['query']),
  'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getSessionSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SessionSummary)],
      ['query'],
    ),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSessionSummary' : IDL.Func([IDL.Text, SessionSummary], [], []),
  'setDailyGoal' : IDL.Func([IDL.Nat], [], []),
  'updateChapter' : IDL.Func([Chapter], [], []),
  'updateDailyActual' : IDL.Func([IDL.Nat], [], []),
  'updateReward' : IDL.Func([Reward], [], []),
  'updateSubject' : IDL.Func([Subject], [], []),
  'updateTest' : IDL.Func([Test], [], []),
  'updateUserProgress' : IDL.Func([UserProgress], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Chapter = IDL.Record({
    'subjectName' : IDL.Text,
    'name' : IDL.Text,
    'totalTopics' : IDL.Nat,
    'notesPdf' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'completedTopics' : IDL.Nat,
  });
  const Time = IDL.Int;
  const QuestionPaper = IDL.Record({
    'pdfBlob' : IDL.Vec(IDL.Nat8),
    'name' : IDL.Text,
    'uploadDate' : Time,
  });
  const RevisionTopic = IDL.Record({
    'topic' : IDL.Text,
    'subject' : IDL.Text,
    'scheduledDate' : Time,
    'isComplete' : IDL.Bool,
  });
  const Reward = IDL.Record({
    'id' : IDL.Text,
    'unlockDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'unlockCondition' : IDL.Text,
    'progress' : IDL.Opt(IDL.Nat),
    'target' : IDL.Opt(IDL.Nat),
    'isUnlocked' : IDL.Bool,
    'bonusXp' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'topicsCovered' : IDL.Text,
    'subject' : IDL.Text,
    'date' : Time,
    'hoursStudied' : IDL.Nat,
  });
  const Subject = IDL.Record({
    'targetCompletionDate' : Time,
    'name' : IDL.Text,
    'totalTopics' : IDL.Nat,
    'completedTopics' : IDL.Nat,
  });
  const Test = IDL.Record({
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'scoredMarks' : IDL.Opt(IDL.Nat),
    'isCompleted' : IDL.Bool,
    'date' : Time,
    'name' : IDL.Text,
    'chapters' : IDL.Vec(IDL.Text),
  });
  const XPResponse = IDL.Record({ 'xp' : IDL.Nat, 'level' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const Goal = IDL.Record({ 'actual' : IDL.Nat, 'dailyGoal' : IDL.Nat });
  const SessionSummary = IDL.Record({ 'content' : IDL.Text });
  const UserProgress = IDL.Record({
    'xp' : IDL.Nat,
    'level' : IDL.Nat,
    'lastStudyDate' : Time,
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChapter' : IDL.Func([Chapter], [], []),
    'addQuestionPaper' : IDL.Func([QuestionPaper], [], []),
    'addRevisionTopic' : IDL.Func([RevisionTopic], [], []),
    'addReward' : IDL.Func([Reward], [], []),
    'addStudySession' : IDL.Func([StudySession], [], []),
    'addSubject' : IDL.Func([Subject], [], []),
    'addTest' : IDL.Func([Test], [], []),
    'addXP' : IDL.Func([IDL.Nat], [XPResponse], []),
    'archiveChapter' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteQuestionPaper' : IDL.Func([IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Text], [], []),
    'deleteTest' : IDL.Func([IDL.Text], [], []),
    'getArchivedChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getCompletedTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getDailyGoal' : IDL.Func([], [Goal], ['query']),
    'getNonCompletedTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getQuestionPapers' : IDL.Func([], [IDL.Vec(QuestionPaper)], ['query']),
    'getRevisionTopics' : IDL.Func([], [IDL.Vec(RevisionTopic)], ['query']),
    'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getSessionSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SessionSummary)],
        ['query'],
      ),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSessionSummary' : IDL.Func([IDL.Text, SessionSummary], [], []),
    'setDailyGoal' : IDL.Func([IDL.Nat], [], []),
    'updateChapter' : IDL.Func([Chapter], [], []),
    'updateDailyActual' : IDL.Func([IDL.Nat], [], []),
    'updateReward' : IDL.Func([Reward], [], []),
    'updateSubject' : IDL.Func([Subject], [], []),
    'updateTest' : IDL.Func([Test], [], []),
    'updateUserProgress' : IDL.Func([UserProgress], [], []),
  });
};

export const init = ({ IDL }) => { return []; };