/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'isCompleted' : boolean,
  'subjectName' : string,
  'totalTopics' : bigint,
  'chapterId' : string,
  'chaptersCompleted' : bigint,
  'notesPdf' : [] | [Uint8Array],
  'completedTopics' : bigint,
  'chapterName' : string,
}
export interface Goal { 'actual' : bigint, 'dailyGoal' : bigint }
export interface QuestionPaper {
  'pdfBlob' : Uint8Array,
  'name' : string,
  'uploadDate' : Time,
}
export interface RevisionTopic {
  'topic' : string,
  'subject' : string,
  'scheduledDate' : Time,
  'isComplete' : boolean,
}
export interface Reward {
  'id' : string,
  'unlockDate' : [] | [Time],
  'name' : string,
  'description' : string,
  'unlockCondition' : string,
  'progress' : [] | [bigint],
  'target' : [] | [bigint],
  'isUnlocked' : boolean,
  'bonusXp' : bigint,
}
export interface StudySession {
  'topicsCovered' : string,
  'subject' : string,
  'date' : Time,
  'hoursStudied' : bigint,
  'errorLog' : [] | [string],
}
export interface Subject { 'name' : string, 'totalChapters' : bigint }
export interface Test {
  'totalMarks' : bigint,
  'subject' : string,
  'scoredMarks' : [] | [bigint],
  'isCompleted' : boolean,
  'date' : Time,
  'name' : string,
  'chapters' : Array<string>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export interface UserProgress {
  'xp' : bigint,
  'level' : bigint,
  'lastStudyDate' : Time,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface XPResponse { 'xp' : bigint, 'level' : bigint }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChapter' : ActorMethod<[Chapter], undefined>,
  'addRevisionTopic' : ActorMethod<[RevisionTopic], undefined>,
  'addReward' : ActorMethod<[Reward], undefined>,
  'addStudySession' : ActorMethod<[StudySession], undefined>,
  'addSubject' : ActorMethod<[string, bigint], undefined>,
  'addTest' : ActorMethod<[Test], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChapter' : ActorMethod<[string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapters' : ActorMethod<[], Array<Chapter>>,
  'getCompletedTests' : ActorMethod<[], Array<Test>>,
  'getNonCompletedTests' : ActorMethod<[], Array<Test>>,
  'getQuestionPapers' : ActorMethod<[], Array<QuestionPaper>>,
  'getRevisionTopics' : ActorMethod<[], Array<RevisionTopic>>,
  'getRewards' : ActorMethod<[], Array<Reward>>,
  'getSessionsWithErrors' : ActorMethod<[], Array<StudySession>>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTodayGoal' : ActorMethod<[], Goal>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[], UserProgress>,
  'getXP' : ActorMethod<[], XPResponse>,
  'incrementTodayHours' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRevisionComplete' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTodayGoal' : ActorMethod<[bigint], undefined>,
  'updateChapterCompletion' : ActorMethod<[string, boolean], undefined>,
  'updateChapterName' : ActorMethod<[string, string], undefined>,
  'updateUserProgress' : ActorMethod<[UserProgress], undefined>,
  'uploadPdf' : ActorMethod<[string, Uint8Array], undefined>,
  'uploadQuestionPaper' : ActorMethod<[QuestionPaper], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];